### PR TITLE
Update ember-cli to 1.13 and the fixture adapter to work with Ember Data 2.0

### PR DESCRIPTION
**Pull request by bmac**

### CODE REVIEW

**Comment by aivanov93** [comment]
Can this be merged?

**Comment by jme783** [comment]
+1

**Comment by Swizz** [comment]
Need travis check success to be merged ?

This fix is needed.

**Comment by bmac** [comment]
@Swizz @jme783. I've been busy with client work and haven't had much time to clean up this pr. If one of you would like to take this branch and get the tests passing I would be happy to cut a release once the changes have been merged.

**Comment by demoneaux** [comment]
Any updates?

**Comment by pangratz** [comment]
@demoneaux just a head up regarding the fixture adapter: it is kind of deprecated in favor of the much more mature [ember-cli-mirage](https://github.com/samselikoff/ember-cli-mirage), [ember-data-factory-guy](https://github.com/danielspaniel/ember-data-factory-guy) and even https://github.com/pretenderjs/pretender. Depending on your use case, I would suggest you try one of those libraries.

**Comment by wdch-nseeley** [comment]
What is a good way to embed static data into your models.  Data not located on the server.  I've traditionally used the fixture adapter, but seems to be out of style now.

**Comment by pangratz** [comment]
@wdch-nseeley `ember-cli-mirage` can be used in production for example, see http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/#enabled. If you don't want to use an additional addon, you can also `store.push` your fixture in the `model()` hook of your application route.

**Comment by Swizz** [comment]
I agree with @wdch-nseeley.

I develop Ember-electron apps, and I commonly use Fixtures to give me a way to enpack statics datas with my app.
I tried Mirage for other projects but I keep in mind that Fixture is more easy to use in this case.

And I do not know if pushing all models separatly is more pleasant as writing a simple array of objects.

**Comment by pangratz** [comment]
@Swizz ok, thanks for bringing up your use case. I can see now how there is still need for this. Please take my statement about the fixture adapter being kind of deprecated with a grain of salt.

I've opened a rebased version of this PR. Can you give this a try and report back if this allows you to use the fixture adapter with `ember-data` 2.x? The location is at `pangratz/ember-data-fixture-adapter#rebased-2.0`...

**Comment by ghost** [comment]
Thanks. I will give it a try.

**Pull request merged**
